server:
  port: 8080

logging:
  level:
    root: DEBUG
  file:
    name: spring.log

spring:
  datasource:

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lms
    username: sa
    password: sa

  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql


#jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lc.lms.pojo

